routes.py
from flask import Blueprint, render_template, request, session, jsonify, redirect, url_for, flash, abort
from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user
from models import User, Recipe, Ingredient, RecipeIngredient, Step, Rating, Comment
from database import db
from werkzeug.utils import secure_filename
import os
from sqlalchemy import and_,or_ ,cast, String, func
from sqlalchemy.orm import contains_eager

UPLOAD_FOLDER = 'static/images/users_avatar'
UPLOAD_RECIPE_FOLDER = 'static/images/recipes_images'


main_blueprint = Blueprint('main', __name__)

@main_blueprint.route('/')
@main_blueprint.route('/home')
def index():
    return render_template('index.html')

@main_blueprint.route('/login')
def login():
    session['next'] = request.args.get('next')
    return render_template('login.html')

@main_blueprint.route('/signup')
def signup():
    return render_template('signup.html')

@main_blueprint.route('/profil', methods = ['POST', 'GET'])
@login_required
def profil():
    return render_template('profil.html', title= "Profile")

@main_blueprint.route('/submit_recipe')
@login_required
def submit_recipe():
    return render_template('submit_recipe.html', title= "Submit Recipe")

@main_blueprint.route('/admin_panel')
@login_required
def admin_panel():
    cocktails = Recipe.query.all()
    users = User.query.all()
    return render_template('admin_panel.html', title="Admin Panel", cocktails=cocktails, users=users)

user_blueprint = Blueprint('user', __name__)
@user_blueprint.route('/new_user', methods = ['POST'])
def new_user():
    if (request.method == 'POST'):
        username = request.form['username']
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        email = request.form['email']
        password = request.form['password']

        n_user  = User(username=username, firstname=first_name, lastname=last_name, email = email, password=password)
 
        db.session.add(n_user)
        db.session.commit()
        flash("Your account has been successfully created", 'success')
        return render_template('login.html', title = "Login")


@user_blueprint.route('/user_login', methods=['POST', 'GET'])
def user_login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        remember = True if request.form.get('remember') else False         
        user = User.query.filter_by(username=username).first()
        if user and user.password == password:
            login_user(user, remember=remember)
            if session.get('next'):
                next_url = session.get('next')
                session.pop('next')
                return redirect(next_url or url_for('main.index'))
            else:
                return redirect(url_for('cocktail.cocktails'))
        else:
            flash('Invalid username or password', 'error')
            if session.get('next'):
                next_url = session.get('next')
                return redirect(url_for('user.user_login', next=next_url))
            else:
                return redirect(url_for('user.user_login'))
    else:
        return render_template('login.html')


@user_blueprint.route('/update_profil_image', methods=['POST', 'GET'])
@login_required
def update_profil_image():
    if request.method == 'POST':
        file = request.files['avatar']
        file_extension = os.path.splitext(file.filename)[1]
        filename = 'avatar_{}{}'.format(current_user.id, file_extension)
        file.save(os.path.join(UPLOAD_FOLDER, filename))
        
        current_user.profile_image = os.path.join('images/users_avatar', filename).replace('\\', '/')
        db.session.commit()
        
        flash('Profile image updated successfully.', 'success')
        return redirect(url_for('main.profil'))

@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('next', None)
    return redirect(url_for('main.index'))





cocktail_blueprint = Blueprint('cocktail', __name__)

@cocktail_blueprint.route('/cocktails')
def cocktails():
    cocktails = Recipe.query.filter_by(valid=True).order_by(func.lower(Recipe.title)).all()
    return render_template('cocktails.html', title="Cocktails", cocktails = cocktails)

@cocktail_blueprint.route('/cocktail/<int:cocktail_id>')
def details_cocktail(cocktail_id):
    cocktail = Recipe.query.filter_by(id=cocktail_id).first()
    if current_user.is_authenticated:
        user_rating = Rating.query.filter_by(user_id=current_user.id, recipe_id=cocktail_id).first()
    else:
        user_rating = 0
    return render_template('details.html', title="Cocktail Details", cocktail = cocktail, user_rating=user_rating)

@cocktail_blueprint.route('/new_cocktail', methods=['POST'])
def new_cocktail():
    if request.method == "POST":
        title = request.form['nom']
        difficulty = request.form['difficulte']
        ingredients_concatenated = request.form['ingredientsConcatenated']
        steps_concatenated = request.form['etapesConcatenated']
        image_file = request.files['image']

        
        new_recipe = Recipe(title=title, difficulty=difficulty, user_id=current_user.id)

        
        ingredients = ingredients_concatenated.split('\n')
        
        for ingredient in ingredients:
            if ':' not in ingredient:
                continue
            ingredient_name, quantity = ingredient.split(':')
            ingredient_obj = Ingredient.query.filter_by(name=ingredient_name).first()
            if not ingredient_obj:
                ingredient_obj = Ingredient(name=ingredient_name)
                db.session.add(ingredient_obj)
                db.session.commit()
            recipe_ingredient = RecipeIngredient(quantity=quantity, ingredient_id=ingredient_obj.id)
            new_recipe.recipe_ingredients.append(recipe_ingredient)

        
        steps = steps_concatenated.split('\n')
        for step_description in steps:
            if step_description.strip():
                step = Step(description=step_description)
                new_recipe.steps.append(step)

        
        if image_file:
            file_extension = os.path.splitext(image_file.filename)[1]
            filename = secure_filename(f"recipe_{title.replace(' ', '_')}_{current_user.username}{os.path.splitext(image_file.filename)[1]}")
            image_file.save(os.path.join(UPLOAD_RECIPE_FOLDER, filename))
            new_recipe.recipe_image = os.path.join('images/recipes_images', filename).replace('\\', '/')

        
        db.session.add(new_recipe)
        db.session.commit()

        flash("Submission of new cocktail recipe successfully completed")

        return redirect(url_for('cocktail.cocktails'))

@cocktail_blueprint.route('/rate_recipe', methods=['POST'])
@login_required
def rate_recipe():
    recipe_id = request.form['recipe']
    existing_rating = Rating.query.filter_by(user_id=current_user.id, recipe_id=recipe_id).first()
    
    if existing_rating:
        flash('Vous avez déjà noté cette recette.', 'error')
        return redirect(url_for('cocktail.details_cocktail', cocktail_id=recipe_id))
    else:
        rating_score = request.form['rating']
        
        new_rating = Rating(score=rating_score, user_id=current_user.id, recipe_id=recipe_id)
        db.session.add(new_rating)
        db.session.commit()
        
        flash('Votre notation a été enregistrée avec succès.', 'success')
        return redirect(url_for('cocktail.details_cocktail', cocktail_id=recipe_id))

@cocktail_blueprint.route('/comment_recipe', methods=['POST'])
@login_required
def comment_recipe():
    recipe_id = request.form['recipe']
    comment_text = request.form['comment']

    existing_rating = Rating.query.filter_by(user_id=current_user.id, recipe_id=recipe_id).first()

    if existing_rating:
        new_comment = Comment(text=comment_text, user_id=current_user.id, recipe_id=recipe_id)
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('cocktail.details_cocktail', cocktail_id=recipe_id))
    else:
        rating_score = request.form['ratings']
        if rating_score is None:
            flash("You must first rate the recipe.",'error')
            return redirect(url_for('cocktail.details_cocktail', cocktail_id=recipe_id))
        
        new_rating = Rating(score=rating_score, user_id=current_user.id, recipe_id=recipe_id)
        new_comment = Comment(text=comment_text, user_id=current_user.id, recipe_id=recipe_id)
        db.session.add(new_rating)
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('cocktail.details_cocktail', cocktail_id=recipe_id))

@cocktail_blueprint.route('/user/<string:username>/cocktails')
def user_cocktails(username):
    user = User.query.filter_by(username=username).first()
    
    if not user:
        abort(404)
    
    user_cocktails = Recipe.query.filter_by(user_id=user.id, valid=True).all()
    
    return render_template('user_cocktails.html', title="User Cocktails", cocktails=user_cocktails, author=user)

@cocktail_blueprint.route('/search_cocktail', methods=['GET', 'POST'])
def search_cocktail():
    if request.method == 'POST':
        search_query = request.form['search_query']
        cocktails = Recipe.query.filter(Recipe.title.ilike(f'%{search_query}%'), Recipe.valid==True).all()
        return render_template('search_results.html', title="Search Results", cocktails=cocktails, search_query=search_query)
    else:
        return render_template('search.html', title="Search Cocktails")

@cocktail_blueprint.route('/async_search_cocktail', methods=['POST', 'GET'])
def async_search_cocktail():
    search_query = request.form.get('async_search_query', '')

    cocktails = Recipe.query.join(Recipe.recipe_ingredients).join(RecipeIngredient.ingredient).filter(
        and_(
            Recipe.valid == True,

templates/admin_filter_table.html
<table class="table table-striped">
    <thead>
        <th>Coktails Name</th>
        <th>Published by</th>
        <th>Difficulty</th>
        <th>Status</th>
        <th></th> 
    </thead>
    <tbody>
        {% for cocktail in cocktails%}
        <tr>
            <td class="fw-bolder">{{cocktail.title}}</td>
            <td>{{cocktail.user.firstname[0]}}. {{cocktail.user.lastname}}</td>
            <td>{{cocktail.difficulty}}</td>
            <td>
                {% if cocktail.valid%}
                <p class="fw-bolder text-success">Approved</p>
                {% else %}
                <p class="fw-bolder text-danger">Not approved</p>
                {% endif %}
            </td>
            <td>
                <a href="{{ url_for('cocktail.details_cocktail', cocktail_id=cocktail.id) }}" class="btn btn-outline-warning"><i class="fas fa-eye"></i></a>
                {% if cocktail.valid%}
                <a href="/cocktail/desapprove/{{cocktail.id}}" class="btn btn-warning" onclick="return confirm('Are you sure to desapprouve?')">Desapprove</a>
                {% else %}
                <a href="/cocktail/approve/{{cocktail.id}}" class="btn btn-success" onclick="return confirm('Are you sure to approve?')">Approve</a>
                {% endif %}
                <a href="/cocktail/delete/{{cocktail.id}}" class="btn btn-danger" onclick="return confirm('Are you sure to delete?')">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/admin_panel.html
{% extends 'layouts.html' %}

{% block content %}

<div class="container-fluid ps-4">
    <div class="mt-2">
        <h4 class="mt-4">Admin Panel</h4>

        <!-- Ajouter le formulaire de filtre -->
        <div class="container mb-4">
            <form id="filter-form" onreset="updateRow()">
                <div class="row">
                    <div class="col-md-4">
                        <label for="author-filter">Published by:</label>
                        <select id="author-filter" class="form-select" name="author" onchange="updateRow()">
                            <option value="">All</option>
                            {% for user in users%}
                            <option value="{{user.id}}">{{user.firstname}} {{user.lastname}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="difficulty-filter">Difficulty:</label>
                        <select id="difficulty-filter" class="form-select" name="difficulty" onchange="updateRow()">
                            <option value="">All</option>
                            <option value="Easy">Easy</option>
                            <option value="Intermediate">Intermediate</option>
                            <option value="Hard">Hard</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="status-filter">Status</label>
                        <select id="status-filter" class="form-select" name="status"  onchange="updateRow()">
                            <option value="">All</option>
                            <option value="Approved">Approved</option>
                            <option value="Not approved">Not approved</option>
                        </select>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12 justify-content-center d-flex">
                        <button type="submit" class="btn btn-primary">Filter</button>
                        <button type="reset" class="btn btn-secondary ms-2">Reset</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="container" id="filtered-results">
            <table class="table table-striped">
                <thead>
                    <th>Coktails Name</th>
                    <th>Published by</th>
                    <th>Difficulty</th>
                    <th>Status</th>
                    <th></th> 
                </thead>
                <tbody>
                    {% for cocktail in cocktails%}
                    <tr>
                        <td class="fw-bolder">{{cocktail.title}}</td>
                        <td>{{cocktail.user.firstname[0]}}. {{cocktail.user.lastname}}</td>
                        <td>{{cocktail.difficulty}}</td>
                        <td>
                            {% if cocktail.valid%}
                            <p class="fw-bolder text-success">Approved</p>
                            {% else %}
                            <p class="fw-bolder text-danger">Not approved</p>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ url_for('cocktail.details_cocktail', cocktail_id=cocktail.id) }}" class="btn btn-outline-warning"><i class="fas fa-eye"></i></a>
                            {% if cocktail.valid%}
                            <a href="/cocktail/desapprove/{{cocktail.id}}" class="btn btn-warning" onclick="return confirm('Are you sure to desapprouve?')">Desapprove</a>
                            {% else %}
                            <a href="/cocktail/approve/{{cocktail.id}}" class="btn btn-success" onclick="return confirm('Are you sure to approve?')">Approve</a>
                            {% endif %}
                            <a href="/cocktail/delete/{{cocktail.id}}" class="btn btn-danger" onclick="return confirm('Are you sure to delete?')">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function(){
        document.getElementById('filter-form').addEventListener('submit', function(event){
            event.preventDefault(); 
            updateRow();
            
        });
    });
    function updateRow(){
        var status = document.getElementById('status-filter').value;
            var author = document.getElementById('author-filter').value;
            var difficulty = document.getElementById('difficulty-filter').value;

            fetch('/filter_cocktails', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    status: status,
                    author: author,
                    difficulty: difficulty
                })
            })
            .then(response => response.text())
            .then(data => {
                document.getElementById('filtered-results').innerHTML = data;
                console.log(data)
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }
</script>

{% endblock %}

templates/async_result.html
{% if cocktails|length == 0 %}

<div>
    <p class="fw-semibold text-center">No results available</p>
</div>

{% endif %}


{% for cocktail in cocktails %}
            <div class="col-3 grid-margin stretch-card">
                <div class="cocktail_card card navlink rounded-4 p-0 overflow-hidden">
                    <div class="card-body p-0">
                        <div class="logo d-flex align-items-center justify-content-center"><i class="fas fa-martini-glass text-white"></i></div>
                        <a href="{{ url_for('cocktail.details_cocktail', cocktail_id=cocktail.id) }}">
                            <div class="rounded-4 overflow-hidden align-items-center justify-content-center d-flex">
                                <img src="{{ url_for('static', filename=cocktail.recipe_image) }}" alt="CocktailGenius Logo">
                            </div>
                        </a>
                        <h1 class="card-title mt-3 text-center">{{ cocktail.title }}</h1>
                        <div class="d-flex justify-content-between pe-3 ps-3">
                            <p><i class="fas fa-martini-glass fs-3"></i> {{ cocktail.difficulty }}</p>
                            <small class=""><i class="fas fa-user-pen fs-1"></i> By <a href="/user/{{ cocktail.user.username }}/cocktails" class="text-warning fw-semibold">{{ cocktail.user.firstname[0] }} {{ cocktail.user.lastname }}</a></small>
                        </div>
                        <div class="d-flex justify-content-between align-items-start pe-3 ps-3">
                            <p class="d-flex align-items-center mt-1">
                                {% set average_rating = cocktail.average_rating() %}
                                {% for i in range(1, 6) %}
                                    {% if average_rating >= i %}
                                        <i class="fas fa-star fs-2 text-warning"></i>
                                    {% elif average_rating > i - 1 and average_rating < i %}
                                        <i class="fas fa-star-half-alt fs-2 text-warning"></i>
                                    {% else %}
                                        <i class="far fa-star fs-2 text-warning"></i>
                                    {% endif %}
                                {% endfor %}
                                <span class="ms-1 fs-3">{{ cocktail.count_ratings() }} ratings</span>
                            </p>
                            <a href="{{ url_for('cocktail.details_cocktail', cocktail_id=cocktail.id) }}" class="fs-2 mt-1 text-success"><i class="fas fa-eye"></i> View details</a>
                        </div>
                    </div>
                </div>
            </div>
{% endfor %}

templates/cocktails.html
{% extends 'layouts.html' %}

{% block content %}

<div class="container-fluid ps-4">
    <div class=" mt-3">
        <h4 class="mt-4">Our Cocktails of the Moment</h4>
        <form action="/async_search_cocktail" method="post" id="async_form"><div class="input-group w-50 m-auto">
            <input type="text" placeholder="Search: ingredients, recipes, ..." class="form-control mt-3" name="async_search_query">
            <div class="input-group-append mt-3">
                <button class="btn btn-success pt-2 pb-2 rounded-right" type="submit" style="height: 38px; width: 80px;">
                  <i class="fas fa-search"></i>
                </button>
            </div>
        </div></form>
        <div id="async_div" class=" container-fluid row mt-5 justify-content-center align-items-center">
            {% for cocktail in cocktails %}
            <div class="col-3 grid-margin stretch-card">
                <div class="cocktail_card card navlink rounded-4 p-0 overflow-hidden">
                    <div class="card-body p-0">
                        <div class="logo d-flex align-items-center justify-content-center"><i class="fas fa-martini-glass text-white"></i></div>
                        <a href="{{ url_for('cocktail.details_cocktail', cocktail_id=cocktail.id) }}">
                            <div class="rounded-4 overflow-hidden align-items-center justify-content-center d-flex">
                                <img class="c_image" src="{{ url_for('static', filename=cocktail.recipe_image) }}" alt="{{cocktail.title}}">
                            </div>
                        </a>
                        <h1 class="card-title mt-3 text-center">{{ cocktail.title }}</h1>
                        <div class="d-flex justify-content-between pe-3 ps-3">
                            <p><i class="fas fa-martini-glass fs-3"></i> {{ cocktail.difficulty }}</p>
                            <small class=""><i class="fas fa-user-pen fs-1"></i> By 
                                <a href="/user/{{ cocktail.user.username }}/cocktails" class="text-warning fw-semibold">
                                    
                                    {{ cocktail.user.firstname[0] }}. {{ cocktail.user.lastname }}
                                </a>
                            </small>
                        </div>
                        <div class="d-flex justify-content-between align-items-start pe-3 ps-3">
                            <p class="d-flex align-items-center mt-1">
                                {% set average_rating = cocktail.average_rating() %}
                                {% for i in range(1, 6) %}
                                    {% if average_rating >= i %}
                                        <i class="fas fa-star fs-2 text-warning"></i>
                                    {% elif average_rating > i - 1 and average_rating < i %}
                                        <i class="fas fa-star-half-alt fs-2 text-warning"></i>
                                    {% else %}
                                        <i class="far fa-star fs-2 text-warning"></i>
                                    {% endif %}
                                {% endfor %}
                                <span class="ms-1 fs-3">{{ cocktail.count_ratings() }} ratings</span>
                            </p>
                            <a href="{{ url_for('cocktail.details_cocktail', cocktail_id=cocktail.id) }}" class="fs-2 mt-1 text-success"><i class="fas fa-eye"></i> View details</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById("async_form");

    form.addEventListener('submit', function(event) {
        event.preventDefault();
        
        const formData = new FormData(form);

        fetch('/async_search_cocktail', {
            method: 'POST',
            body: formData
        })
        .then(response => response.text())
        .then(data => {
            document.getElementById("async_div").innerHTML = data;
        })
        .catch(error => {
            console.error('Error:', error);
        });
    });
});
</script>
{% endblock %}

templates/ff.html
{% extends 'layouts.html' %} 


{% block content%}


<div class="container-fluid ps-4">
    <div class="mt-2">
        
    </div>
</div>


{%endblock%}

templates/submit_recipe.html
{% extends 'layouts.html' %}

{% block content%}
<div class="container-fluid p-2">
    <div class="card col-md-7 m-auto">
        <div class="card-body">
            <form action="{{url_for('cocktail.new_cocktail')}}" id="cocktailForm" method="post" enctype="multipart/form-data">
                <h4 class="text-center">Submit a new cocktail recipe</h4>
                <hr class="mt-1">
                <div class="row">
                    <div class="form-group col-md-7">
                        <label for="nom" class="fw-semibold mb-0">Cocktail Name</label>
                        <input type="text" class="form-control rounded-2" name="nom" required>
                    </div>
                    <div class="form-group col">
                        <label for="difficulte" class="fw-semibold mb-0">Difficulty</label>
                        <select class="form-select rounded-2" name="difficulte" required>
                            <option value="Easy">Easy</option>
                            <option value="Intermediate">Intermediate</option>
                            <option value="Hard">Hard</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="fw-semibold mb-0">Ingredients <small class="fs-3">(For 1 people)</small></label>
                    <div id="ingredients">
                        <div class="ingredient">
                            <div class="input-group">
                                <input type="text" class="form-control rounded-2 col-6 me-2" name="ingredients[]" placeholder="Ingredient Name" required>
                                <input type="text" class="form-control rounded-2 col-5" name="quantites[]" placeholder="Quantity" required>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center"><button type="button" class="btn btn-primary mt-1" id="addIngredient">Add Ingredient</button></div>
                </div>
                <div class="form-group">
                    <label  class="fw-semibold mb-0">Steps</label>
                    <div id="etapes">
                        <div class="etape">
                            <textarea class="form-control rounded-2" name="etapes[]" required></textarea>
                        </div>
                    </div>
                    <div class="d-flex justify-content-center"><button type="button" class="btn btn-primary mt-2" id="addEtape">Add Step</button></div>
                </div>
                <div class="form-group">
                    <label for="image" class="fw-semibold mb-0">Cocktail Image</label>
                    <input type="file" class="form-control rounded-2" name="image" required accept="image/*">
                </div>

                <input type="hidden" id="ingredientsConcatenated" name="ingredientsConcatenated">
                <input type="hidden" id="etapesConcatenated" name="etapesConcatenated">
                <div class="form-group">
                    <button type="button" onclick="concatAndSubmit()" class="btn btn-success col-10 offset-1">Create Recipe</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    // JavaScript to add and remove ingredient and step fields
    document.getElementById("addIngredient").addEventListener("click", function() {
        var ingredients = document.getElementById("ingredients");
        var ingredient = document.createElement("div");
        ingredient.classList.add("ingredient");
        ingredient.innerHTML = `<div class="input-group mt-1">
                                    <input type="text" class="form-control col-6 me-2" name="ingredients[]" placeholder="Ingredient Name" required>
                                    <input type="text" class="form-control col-5 me-2" name="quantites[]" placeholder="Quantity" required>
                                </div>`;
        ingredients.appendChild(ingredient);
        if (ingredients.children.length > 1) {
            var removeButton = document.createElement("button");
            removeButton.type = "button";
            removeButton.classList.add("btn", "btn-danger", "remove", "fw-bolder", "rounded");
            removeButton.textContent = "-";
            ingredient.querySelector(".input-group").appendChild(removeButton);
            removeButton.addEventListener("click", function() {
                ingredient.remove();
            });
        }
    });

    document.getElementById("addEtape").addEventListener("click", function() {
        var etapes = document.getElementById("etapes");
        var etape = document.createElement("div");
        etape.classList.add("etape");
        etape.innerHTML = `<div class="input-group d-flex justify-content-between align-items-center mt-1"><textarea class="form-control col-11" name="etapes[]" required></textarea></div>`;
        etapes.appendChild(etape);
        if (etapes.children.length > 1) {
            var removeButton = document.createElement("button");
            removeButton.type = "button";
            removeButton.classList.add("btn", "btn-danger", "remove", "fw-bolder", "rounded");
            removeButton.textContent = "-";
            etape.querySelector(".input-group").appendChild(removeButton);
            removeButton.addEventListener("click", function() {
                etape.remove();
            });
        }
    });


    function concatAndSubmit() {
        var ingredients = document.getElementsByName("ingredients[]");
        var quantites = document.getElementsByName("quantites[]");
        var etapes = document.getElementsByName("etapes[]");

        var ingredientsConcatenated = "";
        var etapesConcatenated = "";

        // Concatenate values of ingredient fields
        for (var i = 0; i < ingredients.length; i++) {
            ingredientsConcatenated += ingredients[i].value + " : " + quantites[i].value + "\n";
        }

        // Concatenate values of step fields
        for (var j = 0; j < etapes.length; j++) {
            etapesConcatenated += etapes[j].value + "\n";
        }

        // Store concatenated values in hidden fields
        document.getElementById("ingredientsConcatenated").value = ingredientsConcatenated;
        document.getElementById("etapesConcatenated").value = etapesConcatenated;

        // Submit the form
        document.getElementById("cocktailForm").submit();
    }
</script>
{% endblock %}